# Generated by Django 3.2.10 on 2024-10-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedetails',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
