# Generated by Django 5.1.4 on 2026-01-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_devicedetails_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedetails',
            name='location',
            field=models.TextField(default='not available'),
        ),
    ]
