# Generated by Django 5.1.4 on 2026-02-03 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_devicedetails_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
