# Generated by Django 5.1.4 on 2026-02-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_devicedetails_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedetails',
            name='created_at',
        ),
        migrations.AddField(
            model_name='devicedetails',
            name='added_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
