# Generated by Django 5.1.4 on 2026-02-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_remove_devicedetails_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedetails',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
