# Generated by Django 5.1.4 on 2026-02-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_alter_devicedetails_added_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedetails',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='devicedetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
